### ISSUE TITLE
Integration of Issues

### ISSUE THREAD

**Issue by srijanshetty** [SuperteamDAO/reputation-bot#1]
Fetch Issues from all of the repos and share them at `#help-wanted`

**Comment by srijanshetty** [comment]
@0xMukesh

**Comment by 0xMukesh** [comment]
Pretty simple to implement, would need you to create a Discord webhook for the `#help-wanted` channel and we can use the [`sendToDiscord`](https://github.com/SuperteamDAO/reputation-webhook/blob/main/src/services/issues.ts#L35-L43) function to send the issues embed to the `#help-wanted` channel as well.

**Comment by 0xMukesh** [comment]
Is that what you meant or is it something like this? Fetch issues from "all the projects" in the airtable and share a separate embed in `#help-wanted` channel?

**Comment by srijanshetty** [comment]
Yes @0xMukesh

**Comment by 0xMukesh** [comment]
Pushed in commit [`27918e3`](https://github.com/SuperteamDAO/reputation-bot/commit/27918e393644bea9cd56be4944ced64914f88fb7). To make it live for production, add an environment variable named `DISCORD_WEBHOOK_URL` and its value would be the Discord webhook URL for the `#help-wanted` channel.

```env
DISCORD_WEBHOOK_URL=
AIRTABLE_API_KEY=
AIRTABLE_BASE_APP_ID=
GITHUB_TOKEN=
```
